evenements_index:
    path:     /
    defaults: { _controller: "EventBundle:Evenements:index" }
    methods:  GET

evenements_show:
    path:     /{id}/show
    defaults: { _controller: "EventBundle:Evenements:show" }
    methods:  GET

evenements_new:
    path:     /new
    defaults: { _controller: "EventBundle:Evenements:new" }
    methods:  [GET, POST]

evenements_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventBundle:Evenements:edit" }
    methods:  [GET, POST]

evenements_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventBundle:Evenements:delete" }
    methods:  DELETE
participer:
    path:     /participer/{id}
    defaults: { _controller: EventBundle:Evenement:participer }