hotes:
    resource: "@HotesBundle/Resources/config/routing.yml"
    prefix:   /hotes

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /Inbox