app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
relation:
    resource: "@RelationBundle/Resources/config/routing.yml"
    prefix:   /Relation

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Admin

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
