group:
  resource: "@GroupBundle/Resources/config/routing.yml"
  prefix:   /

app:
  resource: "@AppBundle/Resources/config/routing.yml"
  prefix:   /
relation:
  resource: "@RelationBundle/Resources/config/routing.yml"
  prefix:   /Relation
blog:
  resource: "@UserBundle/Resources/config/routing/blog.yml"
  prefix:   /blog
fos_message:
  resource: "@FOSMessageBundle/Resources/config/routing.xml"
  prefix: /groups/messages
admin:
  resource: "@AdminBundle/Resources/config/routing.yml"
  prefix:   /Admin

bon_plans:
  resource: "@BonPlansBundle/Resources/config/routing.yml"
  prefix:   /bonplans

bon_plans:
  resource: "@BonPlansBundle/Resources/config/routing.yml"
  prefix:   /bonplans

user:
  resource: "@UserBundle/Resources/config/routing.yml"
  prefix:   /user

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mgilet_notification:
  resource: "@MgiletNotificationBundle/Controller/"
  prefix: /notifications
