relation_homepage:
    path:     /
    defaults: { _controller: RelationBundle:Acceuil:index }
=demande:
    path:     /demande
    defaults: { _controller: RelationBundle:Default:demande }

demande_notifications:
    path:     /getdemandenotifications
    defaults: { _controller: RelationBundle:Notification:getDemandes }

accept_demande:
    path:     /acceptdemande
    defaults: { _controller: RelationBundle:Default:acceptDemande }

reject_demande:
    path:     /rejectdemande
    defaults: { _controller: RelationBundle:Default:rejectDemande }

ajax_search:
    path:     /search
    defaults: { _controller: RelationBundle:Default:search }
search_result:
    path:     /getresult
    defaults: { _controller: RelationBundle:Default:resultat }

message_data:
    path:     /getmessages
    defaults: { _controller: UserBundle:Message:getMessages }

message_data_all:
    path:     /getallmessages
    defaults: { _controller: UserBundle:Message:getAllMessages }

send_message:
    path:     /sendmessage
    defaults: { _controller: UserBundle:Message:sendMessage }

chat:
    path:     /getmembers
    defaults: { _controller: UserBundle:Message:getChatMemebers }

message_notifications:
    path:     /getmessagenotifications
    defaults: { _controller: RelationBundle:Notification:getMessageNotification }

check_users:
    path:     /checkusers
    defaults: { _controller: RelationBundle:Default:check }

make_accepts_seen:
    path:     /makeacceptsasseen
    defaults: { _controller: RelationBundle:Notification:makeAcceptsAsSeen }

connected_user:
    path:     /user
    defaults: { _controller: UserBundle:Default:getUser }
interaction_homepage:
    path:     /recherche
    defaults: { _controller: RelationBundle:Default:recherche }